### ISSUE TITLE
运行一段无法确定的时间后报错阻塞

### ISSUE THREAD

**Issue by ACyule** [luosaidage/yolov5_onnx_server#2]
因为我是小白, 使用复制博主你的代码直接修改使用
利用了pyinstaller打包后直接放在腾讯云轻量服务器内运行
但是在运行一段时间 可能几个小时, 也有可能几天 会弹出以下报错提示

---------------------------------分割符---------------------------------
Task exception was never retrieved
future: <Task finished name='Task-41541' coro=<IocpProactor.accept.<locals>.accept_coro() done, defined at asyncio\windows_events.py:563> exception=OSError(22, '指定的网络名不再可用。', None, 64, None)>
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 566, in accept_coro
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 555, in finish_accept
OSError: [WinError 64] 指定的网络名不再可用。
Accept failed on a socket
socket: <asyncio.TransportSocket fd=1360, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8000)>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 818, in loop
  File "asyncio\windows_events.py", line 566, in accept_coro
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 555, in finish_accept
OSError: [WinError 64] 指定的网络名不再可用。
---------------------------------分割符---------------------------------

每当出现 '指定的网络名不再可用' api接口就无法使用了, 就好像是端口被使用完了一样......
我尝试百度, 无法得到解决, 报错提示当中提及 socket , 但我并没有写类似的代码, 全是常规的fastapi的 post 和 get
程序窗口也并没有闪退, 类似阻塞状态, 当我把程序关掉重新再打开就可以正常使用, 对此希望博主给予解答

实况截图
![PixPin-2024-12-06-23-39-51](https://github.com/user-attachments/assets/e6cf29e8-96f7-42b5-abdf-9ff97695ff96)

**Comment by luosaidage** [comment]
UP主也没有碰到这样的问题，这可能不是软件问题，你看看是内存爆了吗？建议还是用linux服务器，可以用我的dockerfile文件只做docker镜像会比较稳定。
